kind: pipeline
name: Copo ci

steps:
  - name: 🛠 [Dev] Build
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        - 22
    commands:
      - cd /root/copo_otp
      - git pull
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/copo_otp_api api/otp.go
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/copo_otp_rpc rpc/otp.go
    when:
      branch:
        - master
      event:
        - push

