kind: pipeline
name: copo

clone:
  disable: true

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: host
    username:
      from_secret: user
    password:
      from_secret: pwd
    port:
      from_secret: port
    script:
      - cd /root/copo_otp
      - git pull
    when:
      branch:
      - master
      event:
      - push
trigger:
  branch:
    - master
  event:
    - push
