kind: pipeline
name: copo_bo_api

clone:
  disable: true

steps:
  - name: docker
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/copo_otp
        - git pull
        - docker-compose down
        - docker build -t otp_api -f api/Dockerfile .
        - docker build -t otp_rpc -f rpc/Dockerfile .
        - docker-compose up -d
      when:
        branch:
          - master
        event:
          - push
