kind: pipeline
name: Copo ci

steps:
  - name: 🛠 [Dev] Build
    image: golang
    commands:
      - cd /root/copo_otp
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/copo_otp_api api/otp.go
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/copo_otp_rpc rpc/otp.go
    when:
      branch:
        - master
      event:
        - push

