// Code generated by goctl. DO NOT EDIT!
// Source: otp.proto

package server

import (
	"context"
	"github.com/copo888/copo_otp/rpc/otpclient"

	"github.com/copo888/copo_otp/rpc/internal/logic"
	"github.com/copo888/copo_otp/rpc/internal/svc"
)

type OtpServer struct {
	svcCtx *svc.ServiceContext
}

func NewOtpServer(svcCtx *svc.ServiceContext) *OtpServer {
	return &OtpServer{
		svcCtx: svcCtx,
	}
}

func (s *OtpServer) GenOtp(ctx context.Context, in *otpclient.OtpGenRequest) (*otpclient.OtpGenResponse, error) {
	l := logic.NewGenOtpLogic(ctx, s.svcCtx)
	return l.GenOtp(in)
}

func (s *OtpServer) Validate(ctx context.Context, in *otpclient.OtpVaildRequest) (*otpclient.OtpVaildResponse, error) {
	l := logic.NewValidateLogic(ctx, s.svcCtx)
	return l.Validate(in)
}
