// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	role "github.com/copo888/copo_otp/api/internal/handler/role"
	"github.com/copo888/copo_otp/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/gen",
				Handler: role.GenOtpHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vaild",
				Handler: role.ValidateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/otp"),
	)
}
